### ISSUE TITLE
[Task] Move the Getting started in the Installation Guide

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/documentation#19]
This ticket needs to be done after #18.
- [ ] Move the Getting started file into documentation/source/user/installation-guide/
- [ ] Add Getting started file in documentation/source/user/installation-guide/installation-guide.md to list it in the side menu

**Comment by mfjurbala** [comment]
What do you mean by add? I can {include} getting-started.md in installation-guide.md or copy all of the text into installation-guide.md. Both seem to have the same effect on the side menu.

**Comment by ericbsd** [comment]
Moving  [getting-started.md](https://github.com/ghostbsd/documentation/blob/master/source/user/getting-started.md) in [installation-guide](https://github.com/ghostbsd/documentation/tree/master/source/user/installation-guide)

And adding something in installation-guide.md like below

```{toctree}
:caption: Installation Guide

getting-started
```

**Comment by ericbsd** [comment]
When you do a PR it will build it, so we can see if it is done right.

**Comment by ericbsd** [comment]
I press the wrong button.
