### ISSUE TITLE
[Feature] add support Pt-br on Doc

### ISSUE THREAD

**Issue by GraoMelo** [ghostbsd/documentation#43]
hey good afternoon.
how are translations done, how to send PR to a new language?

**Comment by ericbsd** [comment]
Good question. I would have to find out how we can handle translation with Sphinx.

This https://www.sphinx-doc.org/en/master/usage/advanced/intl.html could be it. I am not sure.

**Comment by GraoMelo** [comment]
Thank you for the feedback.
